import {
    ApplicationCommandDataResolvable,
    ApplicationIntegrationType,
    SlashCommandBuilder,
    SlashCommandStringOption,
    SlashCommandSubcommandBuilder
} from "discord.js";

export const commands: ApplicationCommandDataResolvable[] = [
    new SlashCommandBuilder()
        .setName('hairsalon')
        .setNameLocalization('nl', 'kapper')
        .setDescription('Bjootify Hair Salon commands')
        .setDescriptionLocalization('nl', 'Bjootify Kapper commando\'s')
        .setIntegrationTypes(ApplicationIntegrationType.GuildInstall, ApplicationIntegrationType.UserInstall)
        .addSubcommand(new SlashCommandSubcommandBuilder()
            .setName('search')
            .setNameLocalization('nl', 'zoeken')
            .setDescription('Search for hair salons nearby')
            .setDescriptionLocalization('nl', 'Zoek naar kappers in de buurt')
            .addStringOption(new SlashCommandStringOption()
                .setName('city')
                .setNameLocalization('nl', 'stad')
                .setRequired(true)
            )
        )
        .addSubcommand(new SlashCommandSubcommandBuilder()
            .setName('details')
            .setNameLocalization('nl', 'details')
            .setDescription('Get details of a hair salon')
            .setDescriptionLocalization('nl', 'Bekijk details van een kapper')
            .addStringOption(new SlashCommandStringOption()
                .setName('name')
                .setNameLocalization('nl', 'naam')
                .setDescription("The name of the salon (kebab-case)")
                .setDescriptionLocalization('nl', 'De naam van de kapper (kebab-case)')
            )
            .addStringOption(new SlashCommandStringOption()
                .setName('city')
                .setNameLocalization('nl', 'stad')
                .setDescription("The city of the salon")
                .setDescriptionLocalization('nl', 'De stad van de kapper')
            )
            .addStringOption(new SlashCommandStringOption()
                .setName('salonId')
                .setNameLocalization('nl', 'salonId')
                .setDescription("The ID of the salon")
                .setDescriptionLocalization('nl', 'Het ID van de kapper')
            )
        )
        .addSubcommand(new SlashCommandSubcommandBuilder()
            .setName('select')
            .setNameLocalization('nl', 'selecteer')
            .setDescription('Select a hair salon for ease of use')
            .setDescriptionLocalization('nl', 'Selecteer een kapper voor gemak')
            .addStringOption(new SlashCommandStringOption()
                .setName('name')
                .setNameLocalization('nl', 'naam')
                .setDescription("The name of the salon (kebab-case)")
                .setDescriptionLocalization('nl', 'De naam van de kapper (kebab-case)')
            )
            .addStringOption(new SlashCommandStringOption()
                .setName('city')
                .setNameLocalization('nl', 'stad')
                .setDescription("The city of the salon")
                .setDescriptionLocalization('nl', 'De stad van de kapper')
            )
            .addStringOption(new SlashCommandStringOption()
                .setName('salonId')
                .setNameLocalization('nl', 'salonId')
                .setDescription("The ID of the salon")
                .setDescriptionLocalization('nl', 'Het ID van de kapper')
                .setRequired(true)
            )
        )
];