import {
    ApplicationCommandDataResolvable,
    ApplicationIntegrationType,
    SlashCommandBuilder,
    SlashCommandStringOption,
    SlashCommandSubcommandBuilder,
    SlashCommandSubcommandGroupBuilder
} from "discord.js";

export const applicationCommands: ApplicationCommandDataResolvable[] = [
    new SlashCommandBuilder()
        .setName('hairsalon')
        .setNameLocalization('nl', 'kapper')
        .setDescription('Bjootify Hair Salon commands')
        .setDescriptionLocalization('nl', 'Bjootify Kapper commando\'s')
        .setIntegrationTypes(ApplicationIntegrationType.GuildInstall, ApplicationIntegrationType.UserInstall)
        .addSubcommand(new SlashCommandSubcommandBuilder()
            .setName('search')
            .setNameLocalization('nl', 'zoeken')
            .setDescription('Search for hair salons nearby')
            .setDescriptionLocalization('nl', 'Zoek naar kappers in de buurt')
            .addStringOption(new SlashCommandStringOption()
                .setName('city')
                .setNameLocalization('nl', 'stad')
                .setDescription("The city to search in")
                .setDescriptionLocalization('nl', 'De stad om in te zoeken')
                .setRequired(true)
            )
            .addStringOption(new SlashCommandStringOption()
                .setName('query')
                .setNameLocalization('nl', 'zoekterm')
                .setDescription("The search term to search for")
                .setDescriptionLocalization('nl', 'De zoekterm om naar te zoeken')
            )
        )
        .addSubcommand(new SlashCommandSubcommandBuilder()
            .setName('details')
            .setNameLocalization('nl', 'details')
            .setDescription('Get details of the selected hair salon')
            .setDescriptionLocalization('nl', 'Bekijk details van de geselecteerde kapper')
        )
        .addSubcommandGroup(new SlashCommandSubcommandGroupBuilder()
            .setName('treatment')
            .setNameLocalization('nl', 'behandelingen')
            .setDescription('Hairsalon treatment commands')
            .setDescriptionLocalization('nl', 'Kapper behandeling commando\'s')
            .addSubcommand(new SlashCommandSubcommandBuilder()
                .setName('list')
                .setNameLocalization('nl', 'lijst')
                .setDescription('List all treatments of a hair salon')
                .setDescriptionLocalization('nl', 'Bekijk alle behandelingen van een kapper')
                .addStringOption(new SlashCommandStringOption()
                    .setName('category')
                    .setNameLocalization('nl', 'categorie')
                    .setDescription("The category to view treatments of")
                    .setDescriptionLocalization('nl', 'De categorie om behandelingen van te bekijken')
                )
                .addStringOption(new SlashCommandStringOption()
                    .setName('query')
                    .setNameLocalization('nl', 'zoekterm')
                    .setDescription("The search term to search for")
                    .setDescriptionLocalization('nl', 'De zoekterm om naar te zoeken')
                )
            )
            .addSubcommand(new SlashCommandSubcommandBuilder()
                .setName('select')
                .setNameLocalization('nl', 'selecteer')
                .setDescription('Select a treatment for ease of use')
                .setDescriptionLocalization('nl', 'Selecteer een behandeling voor gemak')
                .addStringOption(new SlashCommandStringOption()
                    .setName('treatment-id')
                    .setNameLocalization('nl', 'behandeling-id')
                    .setDescription("The ID of the treatment")
                    .setDescriptionLocalization('nl', 'Het ID van de behandeling')
                    .setRequired(true)
                )
                .addStringOption(new SlashCommandStringOption()
                    .setName('salon-id')
                    .setNameLocalization('nl', 'salon-id')
                    .setDescription("The ID of the salon")
                    .setDescriptionLocalization('nl', 'Het ID van de kapper')
                )
            )
            .addSubcommand(new SlashCommandSubcommandBuilder()
                .setName('employees')
                .setNameLocalization('nl', 'medewerkers')
                .setDescription('Get employee info of who can perform a treatment')
                .setDescriptionLocalization('nl', 'Bekijk medewerker info van wie een behandeling kan uitvoeren')
                .addStringOption(new SlashCommandStringOption()
                    .setName('salon-id')
                    .setNameLocalization('nl', 'salon-id')
                    .setDescription("The ID of the salon")
                    .setDescriptionLocalization('nl', 'Het ID van de kapper')
                )
                .addStringOption(new SlashCommandStringOption()
                    .setName('treatment-id')
                    .setNameLocalization('nl', 'behandeling-id')
                    .setDescription("The ID of the treatment")
                    .setDescriptionLocalization('nl', 'Het ID van de behandeling')
                )
            )
            .addSubcommand(new SlashCommandSubcommandBuilder()
                .setName('select-employee')
                .setNameLocalization('nl', 'selecteer-medewerker')
                .setDescription('Select an employee for ease of use')
                .setDescriptionLocalization('nl', 'Selecteer een medewerker voor gemak')
                .addStringOption(new SlashCommandStringOption()
                    .setName('employee-id')
                    .setNameLocalization('nl', 'medewerker-id')
                    .setDescription("The ID of the employee")
                    .setDescriptionLocalization('nl', 'Het ID van de medewerker')
                    .setRequired(true)
                )
                .addStringOption(new SlashCommandStringOption()
                    .setName('salon-id')
                    .setNameLocalization('nl', 'salon-id')
                    .setDescription("The ID of the salon")
                    .setDescriptionLocalization('nl', 'Het ID van de kapper')
                )
                .addStringOption(new SlashCommandStringOption()
                    .setName('treatment-id')
                    .setNameLocalization('nl', 'behandeling-id')
                    .setDescription("The ID of the treatment")
                    .setDescriptionLocalization('nl', 'Het ID van de behandeling')
                )
            )
            .addSubcommand(new SlashCommandSubcommandBuilder()
                .setName('availability')
                .setNameLocalization('nl', 'beschikbaarheid')
                .setDescription('Get availability of a treatment')
                .setDescriptionLocalization('nl', 'Bekijk beschikbaarheid van een behandeling')
                .addStringOption(new SlashCommandStringOption()
                    .setName('salon-id')
                    .setNameLocalization('nl', 'salon-id')
                    .setDescription("The ID of the salon")
                    .setDescriptionLocalization('nl', 'Het ID van de kapper')
                )
                .addStringOption(new SlashCommandStringOption()
                    .setName('treatment-id')
                    .setNameLocalization('nl', 'behandeling-id')
                    .setDescription("The ID of the treatment")
                    .setDescriptionLocalization('nl', 'Het ID van de behandeling')
                )
            )
        )
        .addSubcommandGroup(new SlashCommandSubcommandGroupBuilder()
            .setName('notifications')
            .setNameLocalization('nl', 'meldingen')
            .setDescription('Hairsalon treatment availability notification commands')
            .setDescriptionLocalization('nl', 'Kapperafspraak beschikbaarheeid melding commando\'s')
            .addSubcommand(new SlashCommandSubcommandBuilder()
                .setName('add')
                .setNameLocalization('nl', 'toevoegen')
                .setDescription('Add a treatment notification')
                .setDescriptionLocalization('nl', 'Voeg een behandeling melding toe')
                .addStringOption(new SlashCommandStringOption()
                    .setName('salon-id')
                    .setNameLocalization('nl', 'salon-id')
                    .setDescription("The ID of the salon")
                    .setDescriptionLocalization('nl', 'Het ID van de kapper')
                )
                .addStringOption(new SlashCommandStringOption()
                    .setName('treatment-id')
                    .setNameLocalization('nl', 'behandeling-id')
                    .setDescription("The ID of the treatment")
                    .setDescriptionLocalization('nl', 'Het ID van de behandeling')
                )
                .addStringOption(new SlashCommandStringOption()
                    .setName('employee-id')
                    .setNameLocalization('nl', 'medewerker-id')
                    .setDescription("The ID of the employee")
                    .setDescriptionLocalization('nl', 'Het ID van de medewerker')
                )
            )
            .addSubcommand(new SlashCommandSubcommandBuilder()
                .setName('remove')
                .setNameLocalization('nl', 'verwijderen')
                .setDescription('Remove a treatment notification')
                .setDescriptionLocalization('nl', 'Verwijder een behandeling melding')
                .addStringOption(new SlashCommandStringOption()
                    .setName('salon-id')
                    .setNameLocalization('nl', 'salon-id')
                    .setDescription("The ID of the salon")
                    .setDescriptionLocalization('nl', 'Het ID van de kapper')
                )
                .addStringOption(new SlashCommandStringOption()
                    .setName('treatment-id')
                    .setNameLocalization('nl', 'behandeling-id')
                    .setDescription("The ID of the treatment")
                    .setDescriptionLocalization('nl', 'Het ID van de behandeling')
                )
                .addStringOption(new SlashCommandStringOption()
                    .setName('employee-id')
                    .setNameLocalization('nl', 'medewerker-id')
                    .setDescription("The ID of the employee")
                    .setDescriptionLocalization('nl', 'Het ID van de medewerker')
                )
            )
            .addSubcommand(new SlashCommandSubcommandBuilder()
                .setName('list')
                .setNameLocalization('nl', 'lijst')
                .setDescription('List all treatment notifications')
                .setDescriptionLocalization('nl', 'Bekijk alle behandeling meldingen')
            )
            .addSubcommand(new SlashCommandSubcommandBuilder()
                .setName('clear')
                .setNameLocalization('nl', 'leegmaken')
                .setDescription('Clear all treatment notifications')
                .setDescriptionLocalization('nl', 'Verwijder alle behandeling meldingen')
            )
            .addSubcommand(new SlashCommandSubcommandBuilder()
                .setName('enable')
                .setNameLocalization('nl', 'inschakelen')
                .setDescription('Enable treatment notifications')
                .setDescriptionLocalization('nl', 'Schakel behandeling meldingen in')
            )
            .addSubcommand(new SlashCommandSubcommandBuilder()
                .setName('disable')
                .setNameLocalization('nl', 'uitschakelen')
                .setDescription('Disable treatment notifications')
                .setDescriptionLocalization('nl', 'Schakel behandeling meldingen uit')
            )
        )
];